// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "postProduct",
        "description": "",
        "operationId": "postProduct.post./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostProduct"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "PostProduct": {
      "properties": {
        "title": {
          "title": "PostProduct.title",
          "type": "string"
        },
        "description": {
          "title": "PostProduct.description",
          "type": "string"
        },
        "prise": {
          "title": "PostProduct.prise",
          "type": "number"
        },
        "count": {
          "title": "PostProduct.count",
          "type": "number"
        }
      },
      "required": [
        "title",
        "description",
        "prise",
        "count"
      ],
      "additionalProperties": false,
      "title": "PostProduct",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};