service: my-import-service-gena888

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::my-import-service-gena888"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-import-service-gena888/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
  environment:
    SQS_URL: { Ref: SQSQueue }

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-import-service-gena888-queue

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: GET
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: my-import-service-gena888
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
